### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: ../../model/merge_model/xyj_fintune_merge
adapter_name_or_path: ../../model/llm_adapter/xyj_fintune_preference_adapter
template: qwen
finetuning_type: lora
trust_remote_code: true

### export
export_dir: ../../model/merge_model/xyj_fintune_final
export_size: 2
export_device: cpu
export_legacy_format: false
