### model
model_name_or_path: ../../model/base_model/Qwen2.5-7B-Instruct
quantization_bit: 4
quantization_method: bitsandbytes
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: xyj_fintune
template: qwen
cutoff_len: 2048
max_samples: 20000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ../../model/llm_adapter/xyj_fintune_adapter
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: ../../model/llm_adapter/xyj_fintune_adapter

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
num_train_epochs: 7
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 1000
